" Read vim plugins from file
source ~/.vim/plugins.vim

filetype plugin on
" stop that annoying glitch where vim deletes lines on entry
set t_RV= ttymouse=xterm2

""""""""""""""""""""
" Appearance
""""""""""""""""""""

" Spelling corrections
abbr abrr abbr
abbr fuction function
abbr juint junit
abbr hierarcy hierarchy

" C-like indentation
set autoindent
set smartindent
set cindent

" highlight matching search patterns, start searching before pressing enter
set hlsearch
set incsearch

" case insensitive searching, unless an upper case char was specified
set ignorecase
set smartcase

" add line numbers
set number

"always a certain number of lines above/below current cursor position
set scrolloff=1

" ignore warnings if swapfile exists
set shortmess+=A

" 4 spaces per indent 
set tabstop=4
set shiftwidth=4

" visual, bash-like autocomplete
set wildmenu
set wildmode=longest,full

" wrap long lines
set wrap linebreak

" syntax highlighting
syntax enable
set t_Co=256
try
	colorscheme Benokai
	"colorscheme focuspoint
catch
endtry


""""""""""""""""""""
" Functionality
""""""""""""""""""""
" automatically reloads files that have been detected as being changed
set autoread
" automatically write on :make, :next, etc
set autowrite

" backspace skips over indents, EOL, appends, etc
set backspace=2

" if no register specified, copy to system clipboard
set clipboard=unnamedplus

" bash shell
set shell=bash

" open make errors in new split/buffer if not open
set switchbuf=useopen,usetab,split

source ~/.vim/ignores.vim


""""""""""""""""""""
" Keybindings & commands
""""""""""""""""""""
let mapleader=","

" gr for previous tab
map gr gT
" gb for bottom of file
map gb G
" gs to swap two adjacent characters
map gs xph
" 0 jumps to first non-blank character, instead of hard BOL
map 0 ^
" j and k for soft line movement
nmap j gj
nmap k gk

if !exists(':TmuxNavigateRight')
	" tmux navigation will provide the pane navigation, so only map these if tmux isn't in use
	nnoremap <C-H> <C-w>h
	nnoremap <C-J> <C-w>j
	nnoremap <C-K> <C-w>k
	nnoremap <C-L> <C-w>l
endif

" indentation without shift
nnoremap <Leader><Leader> <<
nnoremap <Leader>. >>

" make with ,m; make clean with ,gm
nnoremap <Leader>m :Make <CR>
nnoremap <Leader>gm :Make clean<CR>

" some remaps for NerdCommenter
nnoremap <Leader>ca :call NERDComment('n', "append")<CR>
nnoremap <Leader>cf :call NERDComment('n', "toggle")<CR>

" shortcuts to edit rc files
nnoremap <Leader>ev :e $MYVIMRC<CR>
nnoremap <Leader>ez :e ~/.zshrc<CR>

" ignore accidental uppercase for W and Q
command! Q q
command! W w

" turn off fucking ex mode
"nnoremap Q <nop>
" similar for q:
nnoremap q: <nop>

" buffer delete does not delete window
command! Bd bp|bd #
nnoremap <Leader>d :Bd<CR>



""""""""""""""""""""
" Autocommands
""""""""""""""""""""

" reload vimrc on save
autocmd! BufWritePost ~/.vimrc source $MYVIMRC
"autocmd! BufWritePost ~/.nvimrc source % 

" do similar if saving .tmux.conf
autocmd! BufWritePost ~/.tmux.conf :call VimuxRunCommand("tmux source-file ~/.tmux.conf")

" and similar for .zshrc
autocmd! BufWritePost ~/.zshrc,*.zsh-theme,$DOTFILES/zsh/*.zsh :call VimuxRunCommand("source ~/.zshrc")

" and bashrc, bash aliases
autocmd! BufWritePost ~/.bashrc :call VimuxRunCommand("source ~/.bashrc")
autocmd! BufWritePost ~/.bash_aliases :call VimuxRunCommand("source ~/.bash_aliases")

" session restore on entering Vim
autocmd! VimEnter * call RestoreSess()

" syntax highlighting for snippet files
autocmd! FileType snippet set syntax=snippets
autocmd! BufRead,BufNewFile *.snippets set filetype=snippets
" special settings for editing crontab files
autocmd! BufNewFile,BufRead crontab.* set nobackup | set nowritebackup
" tab settings for editing makefiles
autocmd! FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
" Python - autocapitalise booleans
autocmd! FileType python :iabbrev <buffer> true True| :iabbrev <buffer> false False
" Ruby - capitalise = capitalize
autocmd! FileType ruby :iabbrev <buffer> capitalise capitalize
" Markdown - syntax highlighting
autocmd! BufRead,BufNew *.md set filetype=markdown
" zsh - highlight theme files
autocmd! BufRead,BufNewFile *.zsh-theme set filetype=zsh

let fortran_free_source=1
let fortran_do_enddo=1

" spellcheck for txt files
autocmd! FileType text,markdown setlocal spelllang=en_au
autocmd! FileType help setlocal nospell

""""""""""""""""""""
" Plugin-specific settings
""""""""""""""""""""

""" airline, bufferline, statusline

" always show statusline
set laststatus=2

let g:airline#extensions#bufferline#enabled = 1
let g:airline#extensions#bufferline#overwrite_variables = 0
let g:airline#extensions#whitespace#enabled = 0

let g:airline_section_c = '%n %t%m'
let g:airline_section_y = '%L'
let g:airline_section_z = '%l,%v'
let g:bufferline_echo = 0

""" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"


""""""""""""""""""""
" Functions
""""""""""""""""""""
" Toggle between relative and absolute line numbers
fu! ToggleLineNumbers() 
	if (&relativenumber == 1)
		set norelativenumber
		set number
	else
		set nonumber
		set relativenumber
	endif
endfunction
nnoremap <Leader>l :call ToggleLineNumbers()<CR>

" restore session on entry, but only if no other command line arguments & not in diff mode
fu! RestoreSess()
    if filereadable(getcwd() . '/Session.vim') && !&diff && argc() == 0
        execute 'so %:p:h/Session.vim'
    endif
endfunction
