export TERM="xterm-256color"


# environment variables
export DOTFILES=/home/andrew/.dotfiles
export ZSH=$DOTFILES/zsh

export ANTIGEN=/home/andrew/Programs/antigen
export EDITOR=vim

unset SSH_ASKPASS

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-monokai.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# make sure prompt & colours are initialised BEFORE you start setting prompts
autoload -U colors && colors
autoload -U promptinit

# This *could* be done in a for loop, but I like to specify the order
source $ZSH/antigen.zsh
source $ZSH/aliases.zsh
if [ "$EUID" -ne 0 ]; then
	# don't set autocomplete if running in root privileges
	source $ZSH/completion.zsh
fi

if [ -z $(pidof xcape) ]; then
	$ZSH/xcape.sh
fi

# turn off beep
unsetopt beep

# vim command line editing
bindkey -v
export KEYTIMEOUT=1

# Reenable help command
autoload -U run-help
autoload run-help-git
autoload run-help-svn
autoload run-help-svk
alias help=run-help

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
setopt autocd
setopt extendedglob
setopt HIST_IGNORE_DUPS
unsetopt HIST_VERIFY # make sure this is done last, as OMZ will overwrite it
