# environment variables
export DOTFILES=/home/andrew/.dotfiles
export ZSH=$DOTFILES/zsh

export ANTIGEN=/home/andrew/Programs/antigen
export EDITOR=vim

# if xcape is installed, remap Ctrl keys + CapsLock to be Escape
if [ -n $(which xcape 2>/dev/null) ]; then
	xcape -e 'Control_L=Escape;Control_R=Escape;Caps_Lock=Escape'
fi

# make sure prompt & colours are initialised BEFORE you start setting prompts
autoload -U colors && colors
autoload -U promptinit

# This *could* be done in a for loop, but I like to specify the order
source $ZSH/antigen.zsh
source $ZSH/aliases.zsh
if [ "$EUID" -ne 0 ]; then
	# don't set autocomplete if running in root privileges
	source $ZSH/completion.zsh
fi

# turn off beep
unsetopt beep

# vim command line editing
bindkey -v
export KEYTIMEOUT=1

# Reenable help command
autoload -U run-help
autoload run-help-git
autoload run-help-svn
autoload run-help-svk
alias help=run-help

# History
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt autocd
setopt extendedglob
setopt HIST_IGNORE_DUPS
unsetopt HIST_VERIFY # make sure this is done last, as OMZ will overwrite it
